apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: iam-system

helmCharts:
  - name: keycloak-operator
    repo: https://keycloak.github.io/keycloak-operator
    releaseName: keycloak-operator
    namespace: iam-system
    valuesFile: values.yaml

resources:
  - ../keycloak/example-kc.yaml
  - secrets.yaml

secretGenerator:
  - name: keycloak-db-secret
    literals:
      - username=testuser
      - password=testpassword
  - name: example-tls-secret
    files:
      - tls.crt=../postgres/certificate.pem
      - tls.key=../postgres/key.pem