apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: iam-stack
  namespace: argocd
spec:
  project: iam
  source:
    repoURL: "https://github.com/Mosman97/infrastructure.git"
    targetRevision: main
    path: charts/iam-stack
    helm:
      valueFiles:
      - values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: iam-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true