apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: iam-system

helmCharts:
  - name: keycloak-operator
    repo: https://keycloak.github.io/keycloak-operator
    releaseName: keycloak-operator
    namespace: iam-system
    valuesFile: values.yaml

resources:
  - secrets-template.yaml

secretGenerator:
  - name: keycloak-db-secret
    literals:
      - username=testuser
      - password=testpassword
  - name: example-tls-secret
    files:
      - tls.crt=../certificates/keycloak.local.crt
      - tls.key=../certificates/keycloak.local.key